// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Platform.x86.Instructions
{
	/// <summary>
	/// ReferenceCountAdd
	/// </summary>
	/// <seealso cref="Mosa.Platform.x86.X86Instruction" />
	public sealed class ReferenceCountAdd : X86Instruction
	{
		internal ReferenceCountAdd()
			: base(0, 1)
		{
		}

		public override bool IsCommutative { get { return true; } }

		public override void Emit(InstructionNode node, OpcodeEncoder opcodeEncoder)
		{
			//ADD DWORD [EAX + 4],1
			//This code only for x86 platform

			opcodeEncoder.Append8Bits(0x83);
			opcodeEncoder.Append8Bits(0x40);
			opcodeEncoder.Append8Bits(0x04);
			opcodeEncoder.Append8Bits(0x01);
		}
	}
}
